### ISSUE TITLE
Allowing scripts before and after commands

### ISSUE THREAD

**Issue by frozzare** [go-pkg-org/gopkg#66]
We have `gopkg build` now and it would be useful to allow before and after scripts for build command, we can do this for different commands, e.g `make` 

The naming of the scripts isn't decided but we could use `pre*` for before and `post*` for after

For example

```
$ gopkg build
```

would run

```
$ my-pre-build-script
$ go build
$ my-post-build-script
```

if the scripts exists in the `metadata.yml` file, e.g

```yml
scripts:
  prebuild: my-pre-build-script
  postbuild: my-post-build-script
```
